services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: techfix
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prisma-network

volumes:
  postgres_data:

networks:
  prisma-network:
